import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildCognitiveBank } from "./bank-builders/cognitive.js";
import { buildEmotionalBank } from "./bank-builders/emotional.js";
import { BANK_VERSION } from "./bank-version.js";

const LANGUAGES = ["hu", "en", "de", "it", "es", "zh", "ja", "ar", "pl", "pt", "fr"];
const currentDir = path.dirname(fileURLToPath(import.meta.url));
const outputDir = path.resolve(currentDir, "../public/banks");
const outputFile = path.join(outputDir, "cogniva-banks.v1.js");

const payload = {
  schemaVersion: 1,
  bankVersion: BANK_VERSION,
  languages: LANGUAGES,
  scoring: {
    status: "expert_review_and_pilot_calibration_required",
    model: "equal_item_weights",
    note: "Weights are provisional content-blueprint weights, not population norms."
  },
  tracks: {
    cognitive: {
      formLength: 20,
      domains: ["patterns", "workingMemory", "numericalReasoning", "flexibleThinking"],
      items: buildCognitiveBank()
    },
    emotional: {
      formLength: 24,
      domains: ["selfAwareness", "regulation", "empathy", "relationships"],
      items: buildEmotionalBank()
    }
  }
};

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(
  outputFile,
  `/* Generated by npm run build:banks. Do not edit by hand. */\nwindow.COGNIVA_BANKS_V1 = ${JSON.stringify(payload)};\n`,
  "utf8"
);

console.log(`Built ${payload.tracks.cognitive.items.length} cognitive and ${payload.tracks.emotional.items.length} emotional items.`);
